// Public barrel for @marionette/document-core: the renderer-agnostic document mutation spine (ADR-0001,
// command-history Section 12). Both the editor renderer AND the headless MCP server consume this same
// surface, so a human and an AI drive the SAME commands (user + AI control, LAW 2). NOTE: Mutator,
// createMutator, and DocumentModelInternal are deliberately NOT exported. The only way to obtain a
// Mutator is to be handed one by History during do/undo, which is the structural half of LAW 2.

// Command + history
export type {
  Command,
  CommandContext,
  HistoryPhase,
  HistoryEvent,
  SelectionHint,
  EntityRef,
} from './command/command';
export { CompositeCommand } from './command/composite';
export { History, HISTORY_DEFAULTS } from './command/history';
export type { HistoryDeps } from './command/history';
export { assertInvariants } from './command/invariants';
export {
  CommandTargetMissingError,
  CommandNotAppliedError,
  DocumentInvariantError,
  HistoryReentrancyError,
  ExportValidationError,
  ReparentCycleError,
  AnimationDurationError,
  KeyframeCollisionError,
  MeshTopologyLockedError,
  MeshBindingError,
  ConstraintError,
  SkinError,
  DeformError,
  EffectEditError,
  EffectsAtlasDanglingRegionError,
  SlotEditError,
} from './command/errors';
export type {
  DocumentError,
  MeshBindingErrorReason,
  ConstraintErrorReason,
  SkinErrorReason,
  DeformErrorReason,
  EffectEditErrorReason,
  EffectsValidationLike,
  SlotEditErrorReason,
} from './command/errors';

// Model (read surface + value types; the write surface stays private)
export type {
  BoneEntity,
  SlotEntity,
  RegionAttachmentEntity,
  MeshAttachmentEntity,
  PreservedAttachmentEntity,
  AttachmentEntity,
  MeshGeometry,
  AnimationEntity,
  BoneChannel,
  BoneTimelineSet,
  SlotTimelineSet,
  KeyframeEntity,
  AttachmentFrameEntity,
  KeyframeValue,
  RotateValue,
  Vec2Value,
  ColorValue,
  IkConstraintEntity,
  TransformConstraintEntity,
  SkinEntity,
  IkKeyframeEntity,
  TransformKeyframeEntity,
  DeformKeyframeEntity,
  DeformSkinKey,
  EventAudioValue,
  EventDefEntity,
  EventKeyEntity,
  DrawOrderOffsetEntity,
  DrawOrderKeyEntity,
  DocState,
  PreservedContent,
} from './model/doc-state';
export {
  emptyPreservedContent,
  meshGeometryOf,
  newDocState,
  makeKeyframe,
  makeIkKeyframe,
  makeTransformKeyframe,
  makeDeformKeyframe,
  makeEventDef,
  makeEventKey,
  makeDrawOrderKey,
  cloneEventAudio,
  cloneMetadata,
  emptyAnimationConstraintTimelines,
} from './model/doc-state';
export type { SlotSceneState } from './model/slot-scene';
export {
  defaultSlotSceneState,
  defaultGridConfig,
  defaultWinSequenceConfig,
  defaultFeatureFlowGraph,
  defaultTumbleChoreography,
  emptySceneRefs,
} from './model/slot-scene';
export type {
  Id,
  BoneId,
  SlotId,
  AnimationId,
  KeyframeId,
  IkConstraintId,
  TransformConstraintId,
  SkinId,
  EventDefId,
  EffectId,
  EffectLayerId,
  LifeStopId,
  BundleItemId,
  IdFactory,
} from './model/ids';
export { makeIdFactory } from './model/ids';
export type {
  DocumentReadModel,
  DocSnapshot,
  BoneSnapshot,
  SlotSnapshot,
  AttachmentSnapshot,
  AnimationSnapshot,
  BoneTimelineSnapshot,
  SlotTimelineSnapshot,
  KeyframeSnapshot,
  AttachmentFrameSnapshot,
  IkConstraintSnapshot,
  TransformConstraintSnapshot,
  SkinSnapshot,
  IkTimelineSnapshot,
  TransformTimelineSnapshot,
  DeformTimelineSnapshot,
  IkKeyframeSnapshot,
  TransformKeyframeSnapshot,
  DeformKeyframeSnapshot,
  EventDefSnapshot,
  EventKeySnapshot,
  DrawOrderKeySnapshot,
  DrawOrderOffsetSnapshot,
  SlotSceneSnapshot,
  SymbolAnimSetSnapshot,
  SceneRefEntrySnapshot,
} from './model/read-model';

// Effects model (WP-3.7): the EffectsDocument as id-keyed editable entities, the read surface, the
// snapshots, and the import/export seam. The write surface (EffectsMutator) stays private, exactly like
// the skeletal Mutator: it is reachable only through History during a command's do/undo.
export type {
  EffectEntity,
  EffectLayerEntity,
  EffectLayerBody,
  EmitterLayerBody,
  SpriteAnimatorLayerBody,
  RibbonTrailLayerBody,
  EffectLifeCurveEntity,
  EffectLifeStopEntity,
  LifeCurveField,
  LifeStopValue,
  BundleEntity,
  BundleItemEntity,
  EffectsState,
} from './effects-model/effects-state';
export { makeLifeStop, newEffectsState } from './effects-model/effects-state';
export type {
  EffectsReadModel,
  EffectsSnapshot,
  EffectSnapshot,
  EffectLayerSnapshot,
  LifeCurveSnapshot,
  LifeStopSnapshot,
  BundleSnapshot,
  BundleItemSnapshot,
} from './effects-model/effects-read-model';
export {
  findEffectSnapshot,
  findLayerSnapshot,
  findBundleSnapshot,
  findBundleItemSnapshot,
} from './effects-model/effects-read-model';
export { effectsDocumentToState, loadEffectsState } from './effects-model/effects-import';
export { exportEffects, EffectsExportValidationError } from './effects-model/effects-export';
export { EFFECTS_FORMAT_VERSION } from './effects-model/effects-version';

// Effect-editing commands (WP-3.7): classes for tools/MCP, the registry + spec for the effects round-trip
// harness. The full section-10 command table.
export {
  CreateEffectCommand,
  DeleteEffectCommand,
  RenameEffectCommand,
  SetEffectMetaCommand,
  SetEffectsAtlasCommand,
  AddLayerCommand,
  RemoveLayerCommand,
  ReorderLayersCommand,
  SetLayerFieldCommand,
  SetLayerBlendModeCommand,
  AddLifeStopCommand,
  RemoveLifeStopCommand,
  MoveLifeStopCommand,
  SetLifeStopValueCommand,
  SetLifeStopCurveCommand,
  CreateBundleCommand,
  DeleteBundleCommand,
  AddBundleItemCommand,
  RemoveBundleItemCommand,
  ReorderBundleItemsCommand,
  SetBundleItemCommand,
  buildDefaultLayer,
  withEmitterDrag,
  assertValidStopOrder,
  locateStop,
  atlasKeepingSeedRegions,
  effectsCommandRegistry,
} from './effects-commands';
export type {
  CreateEffectInit,
  EffectMetaPatch,
  NewLayerKind,
  LocatedStop,
  BundleItemInit,
  BundleItemPatch,
  EffectCommandSpec,
  EffectCommandFixture,
} from './effects-commands';

// Commands (classes for tools/MCP, specs/registry for the harness)
export {
  CreateBoneCommand,
  MoveBoneCommand,
  RotateBoneCommand,
  ScaleBoneCommand,
  SetBoneShearCommand,
  SetBoneLengthCommand,
  SetBoneTransformModeCommand,
  NormalizeBoneRotationCommand,
  RenameBoneCommand,
  ReparentBoneCommand,
  DeleteBoneCommand,
  CreateSlotCommand,
  DeleteSlotCommand,
  RenameSlotCommand,
  SetSlotBlendModeCommand,
  SetSlotColorCommand,
  ReorderSlotCommand,
  AddRegionAttachmentCommand,
  RemoveAttachmentCommand,
  SetActiveAttachmentCommand,
  SetAtlasRefCommand,
  SetRegionAttachmentTransformCommand,
  CreateAnimationCommand,
  DeleteAnimationCommand,
  RenameAnimationCommand,
  SetAnimationDurationCommand,
  SetKeyframeCommand,
  MoveKeyframeCommand,
  DeleteKeyframeCommand,
  SetAttachmentKeyframeCommand,
  DeleteAttachmentKeyframeCommand,
  SetCurveCommand,
  DuplicateAnimationCommand,
  PasteKeyframesCommand,
  GenerateMeshFromRegionCommand,
  AddMeshVertexCommand,
  MoveMeshVertexCommand,
  DeleteMeshVertexCommand,
  SetMeshEdgesCommand,
  AutoGridFillMeshCommand,
  AutoPerimeterTraceMeshCommand,
  BindMeshToBonesCommand,
  AddBoneToMeshBindingCommand,
  RemoveBoneFromMeshBindingCommand,
  UnbindMeshCommand,
  AutoWeightFromProximityCommand,
  PaintWeightStrokeCommand,
  NormalizeMeshWeightsCommand,
  CreateIkConstraintCommand,
  SetIkMixCommand,
  SetIkBendPositiveCommand,
  DeleteIkConstraintCommand,
  SetIkKeyframeCommand,
  DeleteIkKeyframeCommand,
  CreateTransformConstraintCommand,
  SetTransformConstraintParamsCommand,
  DeleteTransformConstraintCommand,
  SetTransformKeyframeCommand,
  DeleteTransformKeyframeCommand,
  CreateSkinCommand,
  RenameSkinCommand,
  DeleteSkinCommand,
  SetSkinAttachmentCommand,
  RemoveSkinAttachmentCommand,
  SetDeformKeyframeCommand,
  DeleteDeformKeyframeCommand,
  MoveDeformKeyframeCommand,
  ClearAttachmentDeformCommand,
  SetGridConfigCommand,
  MapSymbolAnimSetCommand,
  CreateWinSequenceCommand,
  SetWinSequenceStepCommand,
  ReorderWinSequenceStepCommand,
  SetEscalationThresholdCommand,
  CreateFeatureFlowStateCommand,
  AddFeatureFlowTransitionCommand,
  DeleteFeatureFlowStateCommand,
  RenameFeatureFlowStateCommand,
  RemoveFeatureFlowTransitionCommand,
  SetTumbleChoreographyCommand,
  assertValidGridConfig,
  preset5x3ReelStrip,
  preset6x5ScatterPay,
  preset7x7Cluster,
  wrapDegrees,
  commandRegistry,
  findBoneSnapshot,
  findSlotSnapshot,
  findAttachmentSnapshot,
  findAnimationSnapshot,
} from './commands';
export type {
  BoneGeometry,
  SlotInit,
  RegionAttachmentInit,
  RegionTransform,
  KeyframeTarget,
  PastedKeyframe,
  MeshInit,
  MeshAutoFill,
  BindWeightMode,
  PaintMode,
  WeightDab,
  TransformConstraintParams,
  TransformKeyframeMix,
  MapSymbolAnimSetInit,
  CommandSpec,
  CommandFixture,
} from './commands';

// Pure weight-math helpers (WP-2.3 / WP-2.4): distance-to-segment plus influence normalize / cap /
// finalize. Exposed so the editor weight tools and tests share the exact math the commands use.
export {
  distanceToSegment,
  normalizeInfluences,
  capInfluences,
  finalizeVertexWeights,
} from './weights';
export type { BoneInfluence } from './weights';

// Save / load seam
export type { DocumentEnvironment, Document } from './save-load';
export {
  createDocument,
  loadDocument,
  loadDocumentWithEffects,
  effectsStateFromDocument,
  exportDocument,
  exportSlotSceneDocument,
  loadSlotSceneState,
  SlotSceneDocumentError,
} from './save-load';
export type { SlotSceneDocumentErrorCode } from './save-load';
